server:
  port: 4000
  ssl:
    key-store-type: JKS
    key-store: classpath:ssl/server/127.0.0.1-ssl-server.jks
    key-store-password: 127
    key-password: 127
    trust-store-type: JKS
    trust-store: classpath:ssl/server/127.0.0.1-ssl-server-trust.jks
    trust-store-password: 127
    client-auth: need

spring:
  application:
    name: anything-lab
  data:
    mongodb:
      host: 172.16.157.239
      port: 6383
      username: root
      password: 2ICb6XyPJgdv
      database: admin

yaml-config:
  person-map:
    1张三:
      name: 张三
      age: 28